### ISSUE TITLE
Implement calibration of purchase probabilities for "too cheap"

### ISSUE THREAD

**Issue by ejuliaschulz** [max-alletsee/pricesensitivitymeter#21]
Hello Max,
Awesome package! 
I was wondering if there is a way to calibrate the purchase probabilities for "too cheap" to a different value than 0.
Right now you state: 
"The purchase probability at the respondent’s "too cheap" and "too expensive" price are defined as 0. The main logic is that the "too expensive" price point is prohibitively expensive for the respondent and a price at the "too cheap" price level raises doubts about the product quality." which I totally get. 
For other tools using the PSM, "too cheap" can be set to 1, resulting in a descending curve for the purchase intention, which sometimes can make more sense.
Is this something that could be added?
Thank you for your work.

**Comment by max-alletsee** [comment]
Hello @ejuliaschulz,

**Comment by max-alletsee** [comment]
Hello @ejuliaschulz,

thanks for your message and that you like this package.
You may have seen that the package allows to run the analysis without a "too cheap" price point. This means that some of the points will not be calculated (as the corresponding data does not exist) and I think this is a clean solution. It's true, however, that this is not considered for purchase probabilities.

While it's technically possible to implement a probability for the "too cheap" and for the "too expensive" price point which is different from zero, I'm a bit hesitant and would like to understand the context a bit better:

1. Which other PSM tool is implementing this?
2. Which real-life examples of products or categories are used for the scenario you're describing?
3. Is there a reason why this is a probability of 1 and not, for instance, the same probability as for the "cheap / good deal" price?
4. Are there scenarios where you would like to modify the purchase probability of the "too expensive" price?

**Comment by ejuliaschulz** [comment]
Hi @max-alletsee 
sorry for responding so late to your questions.
I'm using the PSM in a rather classical market research approach to evaluate optimum price ranges but also purchase probabilities for different price points, mostly for consumer goods. I agree that depending on the context, one might argue that a price "too cheap" has a purchase probability of 0. But other theories state that the lower the price, the higher the purchase intent, and thus the maximum purchase intention calibration point (e.g. 1) would be applied (which would later be multiplied by the original 5 point calibration vector, as a standard 0.7 for example). 
To describe my context a bit better, I'm searching to replicate the "basic" approach that Sawtooth provides [here](https://sawtoothsoftware.com/resources/software-downloads/tools/van-westendorp-price-sensitivity-meter). They have advanced settings to "play" with the Newton-Miller-Smith calibration. Also, in their output, we rather see the cumulative purchase intent for a price point. I tried to run your code in comparison for a specific study and could somehow not figure out how to interpret the output for purchase intention from your code, as the sum of all purchase intention data did not reflect a cumulative purchase intent, neither did each individual data point seem to reflect a cumulative purchase intent. What I expected was indeed a rather simple interpretation like sawtooth provides in the example mentioned above.
In the meantime I worked on some code in R myself to replicate a bit what was done in the Sawtooth example, but I'd really like to understand how to use your code properly. I also think that I found the line of code where you set the assumption for the NMS extension and setting both "too cheap" and "too expensive" to 0. So adding an additional parameter could work, but of course I'd like to understand your interpretation of the resulting Purchase Intent before.
Thanks!

**Comment by max-alletsee** [comment]
Apologies for my late answer, life got in the way (big time).

I wanted to let you know that v1.3.0 of the package includes the option to adjust this behavior via two additional parameters, `pi_calibrated_toocheap` and `pi_calibrated_tooexpensive`. Both accept values between 0 and 1 for specifying the probability of purchase at the "too cheap" and "too expensive" price, respectively. By default, they are set to zero.

v1.3.0 is currently on the way to CRAN and should be available there within the next days.

**Comment by ejuliaschulz** [comment]
Brilliant, thank you Max.
